# Pumps
PLANT_A_PUMP_PIN = 12
PLANT_B_PUMP_PIN = 16
PLANT_C_PUMP_PIN = 20
PLANT_D_PUMP_PIN = 21

# Humidity Sensors
PLANT_A_HUMSENSOR_SPI_CHANNEL = 0
PLANT_B_HUMSENSOR_SPI_CHANNEL = 1
PLANT_C_HUMSENSOR_SPI_CHANNEL = 2
PLANT_D_HUMSENSOR_SPI_CHANNEL = 3

# Water Level Sensor
WATER_LEVEL_SENSOR_SPI_CHANNEL = 4

# Light Sensor
LIGHT_SENSOR_SPI_CHANNEL = 5