# Pumps
PLANT_A_PUMP_PIN = 12
PLANT_B_PUMP_PIN = 16
PLANT_C_PUMP_PIN = 20
PLANT_D_PUMP_PIN = 21

# Humidity Sensors
PLANT_A_HUMSENSOR_PIN = 24
PLANT_B_HUMSENSOR_PIN = 25
PLANT_C_HUMSENSOR_PIN = 8
PLANT_D_HUMSENSOR_PIN = 7

# Light Sensor
LIGHT_SENSOR_PIN = 5